apiVersion: v1
data:
  mysql-root-password: TVlTUUxfUk9PVF9QQVNTV09SRA==
kind: Secret
metadata:
  name: operator-workshop-mysql
  namespace: default
type: Opaque

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: operator-workshop-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-workshop-mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: operator-workshop-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: operator-workshop-mysql
        image: mysql:5.7.20
        imagePullPolicy: IfNotPresent
        name: operator-workshop-mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: operator-workshop-mysql
  namespace: default
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: operator-workshop-mysql
  type: NodePort
