apiVersion: v1
data:
  postgres-password: b3BlcmF0b3Itd29ya3Nob3A=
kind: Secret
metadata:
  name: workshop-postgres
  namespace: default
type: Opaque

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workshop-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: workshop-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: workshop-postgres
        image: postgres:9.6.2
        imagePullPolicy: IfNotPresent
        name: workshop-postgres
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: workshop-postgres
  namespace: default
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: workshop-postgres
  type: NodePort
